import numpy as np
import torch
import random


def reproducibility(seed):
    """
    :param: set seed for experiment reproducibility

    By setting the random seed for these libraries, it can be ensure that any random numbers generated by the code
    will be the same every time you run it, as long as it is use the same seed. This is important for debugging and
    reproducing experimental results
    """

    # for torch
    torch.manual_seed(seed)

    # for numpy
    np.random.seed(seed)

    # for random
    random.seed(seed)

    # for cuda
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.enabled = False
